#!/bin/sh

REPO_DIR="$HOME/git-activity-mirror"
PUSH_SCRIPT_PATH="$REPO_DIR/publish-activity.sh"

if [ ! -d "$REPO_DIR" ]; then
  echo "Warning: Sync repository path is not correct"
  exit 0
fi

GIT_REMOTE_ORIGIN_URL=$(git config --get remote.origin.url)
TARGET_REMOTE_ORIGIN_URL=$(git -C "$REPO_DIR" config --get remote.origin.url)
if [ "$GIT_REMOTE_ORIGIN_URL" = "$TARGET_REMOTE_ORIGIN_URL" ]; then
  exit 0
fi

GIT_USER_EMAIL=$(git config --get user.email)
TARGET_USER_EMAIL=$(git -C "$REPO_DIR" config --get user.email)
if [ "$GIT_USER_EMAIL" = "$TARGET_USER_EMAIL" ]; then
  case "$GIT_REMOTE_ORIGIN_URL" in
  *github*)
    exit 0
    ;;
  *) ;;
  esac
fi

if [ ! -f "$PUSH_SCRIPT_PATH" ]; then
  echo "Warning: Push script path is not correct"
  exit 0
fi

sh "$PUSH_SCRIPT_PATH"

exit $?
