#!/bin/sh

if [ -z "$ACTIVITY_REPO_DIR" ]; then
  echo "Warning: ACTIVITY_REPO_DIR environment variable is not set. Skipping activity sync."
  exit 0
fi

PUBLISH_ACTIVITY_SCRIPT="$ACTIVITY_REPO_DIR/publish-activity.sh"
GIT_REMOTE_ORIGIN_URL=$(git config --get remote.origin.url)
TARGET_REMOTE_ORIGIN_URL=$(git -C "$ACTIVITY_REPO_DIR" config --get remote.origin.url)

if [ "$GIT_REMOTE_ORIGIN_URL" = "$TARGET_REMOTE_ORIGIN_URL" ]; then
  exit 0
fi

GIT_USER_EMAIL=$(git config --get user.email)
TARGET_USER_EMAIL=$(git -C "$ACTIVITY_REPO_DIR" config --get user.email)

if [ "$GIT_USER_EMAIL" = "$TARGET_USER_EMAIL" ]; then
  case "$GIT_REMOTE_ORIGIN_URL" in
  *github*)
    exit 0
    ;;
  *) ;;
  esac
fi

if [ ! -f "$PUBLISH_ACTIVITY_SCRIPT" ]; then
  echo "Warning: Publish activity script path is not correct"
  exit 0
fi

sh "$PUBLISH_ACTIVITY_SCRIPT"

exit $?
